version: '3.4'


services: 
   todo-app-api:
         image: todo-app-api
         build:
          context: ./libreria.WebApi
          dockerfile: Dockerfile
         ports:
           - "8980:80"
         networks:
           - mynetwork
networks:
   mynetwork:
    driver: bridge
